name: Release

on:
  push:
    branches: [main]
    paths:
      - 'Info.plist'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    environment: release-macOS
    uses: rxliuli/swift-rel/.github/workflows/release.yml@main
    with:
      app-name: AppDowngrader
      version-file: Info.plist
      cask: app-downgrader
      tap: rxliuli/homebrew-tap
      bins-dir: Contents/Resources/AppDowngrader_AppDowngrader.bundle/bin
      entitlements: AppDowngrader.entitlements
      signing-identity: 'Developer ID Application: KAI WANG (N2X78TUUFG)'
    secrets: inherit
